- name: 'ensure that the /tmp/aash link removed'
  become: false
  raw: rm -f /tmp/aash
  ignore_errors: true

- name: 'ensure that the /tmp/aash link exist'
  become: false
  raw: ln -s /bin/sh /tmp/aash
  ignore_errors: true


- name: 'Copy main executable for ep2 (EP2430.20170824-015207-343.gold.tar.gz) from sources to enspoints'
  become: true
  copy: 
    src: files/EP2430.20170824-015207-343.gold.tar.gz
    dest: /tmp
    owner: root
    group: root
    mode: 0755

- name: 'unzip and untar the deliverable script'
  shell: "tar -zxvf EP2430.20170824-015207-343.gold.tar.gz"
  args:
    chdir: /tmp/

- name: 'Execute the script in nohup mode'
  become: true
  shell: "nohup sh EP2_Driver.sh -P -o /tmp/ep2scan_$(uname -n) &"
  args:
    chdir: /tmp/app/EP2Source/EP2_CORE_BASH/

- name: 'ensure that the /tmp/aash link removed'
  become: true
  raw: rm -f /tmp/aash
  ignore_errors: true
