
- name: 'Copy lssec files with latest database(Please update database as per requirement)  from sources to enspoints'
  become: true
  copy: 
    src: files/lssec
    dest: /tmp/
    owner: root
    group: root
    mode: 0755
- name: 'Copy lssecfix script from sources to enspoints'
  become: true
  copy:
    src: files/lssecfix.sh
    dest: /tmp/
    owner: root
    group: root
    mode: 0755

- name: 'Execute the lssecfix script to generate report'
  become: true
  shell: "sh lssec/bin/lssecfixes >lsreport_$(uname -n).txt "
  args:
    chdir: /tmp/

- name: 'Find the lssec report '
  shell: "find /tmp/lsreport_$(uname -n).txt"
  register: findresult

- name: 'Checking the result'
  debug:
    msg: "{{ item }}"
  with_items: "{{ findresult.stdout_lines }}"

- name: 'Copy resule file from the endpoint to local machine'
  become: true
  fetch: 
    src: "{{ item }}"
    dest: /tmp/lssec/RESULTS/
  with_items: "{{ findresult.stdout_lines }}"

- name: 'Execute the lssecfix script to get applicable advisiory '
  become: true
  shell: "sh lssecfix.sh"
  args:
    chdir: /tmp/
  register: advisiory_result
- name: 'List the advisiories'
  debug:
    msg: "{{ item }}"
  with_items: "{{ advisiory_result.stdout_lines }}"



