#  Disable ssh root login as soon as the server is up
#  Add list of sevices that you wish to start post reboot and script to start application post reboot
#  Run post check script to gather system state and config
#  All the above will be executed only if server is registered and packages are found to update

- stat: path=/tmp/postcheck
  register: postflag
  tags: postpatch
- name: send mail to admin reporting issue with server
  mail:
    host: "{{ relay_server }}"
    port: 25
    to: "{{ mail_id }}"
    subject: System {{ ansible_hostname }} reported issue
    body: " System {{ ansible_hostname }} perform manual check for this server. "
  delegate_to: localhost
  when: not postflag.stat.exists

- block:
  - name: disable root login after patching
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present backup=yes
    notify:
      - restart sshd
    tags: postpatch

#  Add list of services that you wish to start post reboot, you can also execute scripts to start application post reboot
  - name: start monitoring service if not started
    service:
      name: zabbix-agent
      state: started
    ignore_errors: yes
    tags: postpatch

  - name: run post-check.sh after patching to capture data
    script: ./files/post-check.sh
    ignore_errors: yes
    tags: postpatch
  when: postflag.stat.exists
