- hosts: oracle
  become: yes
  vars:
    relay_server: relayserver.domain.com
    mail_id: emailaddress@domain.com
  
  roles:
    - zyppcheck
    - prepatch
    - patch
    - postpatch
    - deviation
